# Generated by Django 2.2.1 on 2020-03-29 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0002_auto_20200329_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='additional_skill',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/taborns'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='instagram',
            field=models.URLField(default='https://www.facebook.com/taborns'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twitter',
            field=models.URLField(default='https://www.facebook.com/taborns'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='languages',
            field=models.ManyToManyField(related_name='users', to='gocasting.Language'),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='gallery/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='additional_skills',
            field=models.ManyToManyField(related_name='users', to='gocasting.AdditionalSkill'),
        ),
    ]
