# Generated by Django 2.2.1 on 2020-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0003_auto_20200329_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CastTag',
            new_name='InterestTag',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='intersted_in',
            field=models.ManyToManyField(related_name='users', to='gocasting.InterestTag'),
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
