# Generated by Django 2.2.1 on 2020-03-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0004_auto_20200329_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='weight',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
