# Generated by Django 2.2.1 on 2020-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0006_auto_20200329_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='castinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='castinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
