# Generated by Django 2.2.1 on 2020-04-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0009_auto_20200331_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='profiles/')),
            ],
        ),
    ]
