# Generated by Django 2.2.1 on 2020-04-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0010_picturearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castinfo',
            name='profile_picture',
            field=models.CharField(max_length=150),
        ),
    ]
