# Generated by Django 2.2.1 on 2020-04-02 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0013_agentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress_availables', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress_available_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
