# Generated by Django 2.2.1 on 2020-05-19 16:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0016_auto_20200519_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('requirement', ckeditor_uploader.fields.RichTextUploadingField()),
                ('address', models.CharField(max_length=130)),
                ('gender', models.CharField(choices=[('all', 'All'), ('female', 'Female'), ('female', 'Female')], max_length=12)),
                ('start_age', models.IntegerField()),
                ('end_age', models.IntegerField()),
                ('payment', models.CharField(max_length=150)),
                ('closes_on', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='gocasting.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='gocasting.Job')),
            ],
        ),
    ]
