# Generated by Django 2.2.1 on 2020-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0018_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
