# Generated by Django 2.2.1 on 2020-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0019_job_is_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterField(
            model_name='job',
            name='end_age',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('all', 'All'), ('female', 'Female'), ('male', 'Male')], max_length=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_age',
            field=models.IntegerField(default=0),
        ),
    ]
