# Generated by Django 2.2.1 on 2020-05-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gocasting', '0020_auto_20200520_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cast',
            new_name='applicant',
        ),
    ]
